services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/marketolog
      - POSTGRES_DB=marketolog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - marketolog_network
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    networks:
      - marketolog_network
    depends_on:
      - backend
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=marketolog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    networks:
      - marketolog_network

networks:
  marketolog_network: